#!/usr/bin/env python3
"""
export_bible_data.py - Developer Tool: Export Bible Database for Distribution

This script exports the Bible SQLite database to a compressed SQL dump
suitable for distribution via GitHub Releases.

Usage:
    python3 export_bible_data.py

Output:
    - data/bible_data.sql.gz (compressed SQL dump)
    - data/checksums.txt (SHA256 checksums for verification)

Author: Andrew Hopkins
"""

import os
import subprocess
import hashlib
import sys

def calculate_checksum(filepath):
    """Calculate SHA256 checksum of a file"""
    sha256_hash = hashlib.sha256()
    with open(filepath, 'rb') as f:
        for byte_block in iter(lambda: f.read(4096), b''):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()

def export_database():
    """Export SQLite database to compressed SQL dump"""
    print("=" * 70)
    print("Bible Search Lite - Database Exporter")
    print("=" * 70)
    print()

    # Check if database exists
    db_path = 'database/bibles.db'
    if not os.path.exists(db_path):
        print(f"❌ Error: Database not found at {db_path}")
        print("   Please make sure the database exists in the database/ directory.")
        sys.exit(1)

    # Get database size
    db_size_mb = os.path.getsize(db_path) / (1024 * 1024)
    print(f"📊 Database size: {db_size_mb:.1f} MB")
    print()

    # Create output directory
    os.makedirs('data', exist_ok=True)

    # Step 1: Create SQL dump
    print("📤 Step 1/3: Creating SQL dump...")
    dump_file = 'data/bible_data.sql'

    try:
        with open(dump_file, 'w') as f:
            result = subprocess.run(
                ['sqlite3', db_path, '.dump'],
                stdout=f,
                stderr=subprocess.PIPE,
                text=True
            )

        if result.returncode != 0:
            print(f"❌ Error creating SQL dump: {result.stderr}")
            sys.exit(1)

        dump_size_mb = os.path.getsize(dump_file) / (1024 * 1024)
        print(f"   ✅ Created: {dump_file} ({dump_size_mb:.1f} MB)")
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)

    # Step 2: Compress SQL dump
    print("\n🗜️  Step 2/3: Compressing SQL dump...")

    try:
        subprocess.run(
            ['gzip', '-f', '-9', dump_file],  # -9 for maximum compression
            check=True
        )

        compressed_file = dump_file + '.gz'
        compressed_size_mb = os.path.getsize(compressed_file) / (1024 * 1024)
        compression_ratio = (1 - compressed_size_mb / dump_size_mb) * 100

        print(f"   ✅ Created: {compressed_file}")
        print(f"   📦 Compressed size: {compressed_size_mb:.1f} MB")
        print(f"   💾 Compression ratio: {compression_ratio:.1f}%")
    except Exception as e:
        print(f"❌ Error compressing: {e}")
        sys.exit(1)

    # Step 3: Generate checksums
    print("\n🔒 Step 3/3: Generating checksums...")

    checksum = calculate_checksum(compressed_file)

    checksum_file = 'data/checksums.txt'
    with open(checksum_file, 'w') as f:
        f.write(f"# SHA256 Checksums for Bible Search Lite Data Files\n")
        f.write(f"# Generated by export_bible_data.py\n\n")
        f.write(f"bible_data.sql.gz: {checksum}\n")

    print(f"   ✅ Created: {checksum_file}")
    print(f"   🔑 SHA256: {checksum[:16]}...")

    # Summary
    print("\n" + "=" * 70)
    print("✅ Export Complete!")
    print("=" * 70)
    print(f"\nFiles created in 'data/' directory:")
    print(f"  • bible_data.sql.gz ({compressed_size_mb:.1f} MB)")
    print(f"  • checksums.txt")
    print()
    print("Next steps:")
    print("  1. Create a GitHub Release (e.g., v1.0)")
    print("  2. Upload bible_data.sql.gz to the release")
    print("  3. Upload checksums.txt to the release")
    print("  4. Users can run setup.py to install")
    print()
    print("GitHub Release URL format:")
    print("  https://github.com/andyinva/bible-search-lite/releases/download/v1.0/bible_data.sql.gz")
    print()

if __name__ == "__main__":
    export_database()
